esphome:
  includes:
    - common/libs/wifi_icon.h

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret sk_wifi_ssid
      password: !secret sk_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} AP"
    password: "1234567890"

captive_portal:

sensor:
    # Diagnostic sensors
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: wifi_signal # Reports the WiFi signal in %
    name: "WiFi signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    id: wifi_signal_pct
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    type: timestamp # Requires Time component
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "Internal Temperature"
    entity_category: "diagnostic"

# Web page
web_server:
  port: 80
  log: false
  version: 3